options:
  formatter: stylish
  cache-config: false
  merge-default-rules: false
files:
  include: 'app/**/*.s+(a|c)ss'
  ignore: 'app/global.scss'
rules:
  no-color-keywords: 1
  class-name-format: camelcase
  empty-args: true
  empty-line-between-blocks: true
  final-newline: true
  force-pseudo-nesting: true
  force-element-nesting: true
  hex-notation: lowercase
  no-ids: true
  no-duplicate-properties: true
  no-empty-rulesets: true
  no-misspelled-properties: true
  no-trailing-whitespace: true
  no-trailing-zero: true
  no-universal-selectors: true
  no-vendor-prefixes: true
  one-declaration-per-line: true
  property-sort-order: alphabetical
  space-before-brace: true
  zero-unit: true
  space-before-colon: true