language: node_js
node_js:
  - '6.10'
before_install: npm i -g yarn nodemon tslint typescript webpack
install: yarn
jobs:
  include:
    - stage: build
      script: yarn build
    - stage: lint
      script: yarn lint
